### ISSUE TITLE
Send/Receive messages from E39 cluster out of car

### ISSUE THREAD

**Issue by MorGuux** [just-oblivious/arduino-ibustrx#2]
Hi, I've got an pre 09/97 E39 HIGH (no CANBUS) cluster, and I would like to experiment with sending/receiving IBUS messages. I haven't had any luck with using this library, but I tried using just a general software serial read/write test and managed to get some data (using pin 10 as RX, 11 as TX on Uno). 

When I connect power to the cluster, I get a few bits of English (RANGE ---, MPG 1, etc), but after that, it's just a load of nonsense (⸮⸮⸮⸮⸮⸮).

Because my cluster is not connected to the car, I was wondering if it's still possible to send IBUS messages to it directly. My aim is to be able to display alerts on the OBC text bar from a program on my PC.

Do you know what I can do to get your library to interface correctly, and maybe a sample code or IBUS message I could use?

Any help would be appreciated!
Morgan

**Comment by just-oblivious** [comment]
Hi Morgan,

Unfortunately I don't have a cluster to test with. The only command supported by my E46 cluster is the "set time" command (which worked fine with this library).

I don't know any of the commands for controlling the cluster display, but I do know that the cluster occasionally transmits trip info as ASCII text over the IBUS (to be displayed on the center TFT screen, if equipped).

The cluster also broadcasts information that isn't plain ASCII text (speed, RPM, temps, etc.), that could be the captured 'nonsense' that you're seeing.

It should work fine outside the car. You've got to make sure that the IBUS is reading +12v when idle, and that all the grounds are tied together.

Don

**Comment by MorGuux** [comment]
Hi Don,

It's been a while since I experimented with my E39 cluster.

It was out of the car, bench-testing on my desk using a 12V PSU. The IBUS was reading 12V when the cluster was powered and I constructed a resistor ladder to step down the voltage for use with my Arduino UNO.

I had no luck with using your library, but there was no example on just printing received data. I did not know any message IDs, source, destination etc, so I just wanted to get all data. As I mentioned, I saw some readable words, but most was gibberish. I knew the baud rate was correct, as I wouldn't have saw some complete words otherwise.

One thing I was curious about. Since the cluster was being tested outside the car, does that affect the message IDs? What ID must I use to access it. I think the IKE is 80, but that's in the car. To access directly, do you negate that, or leave it in. I'm unexperienced :)

All GNDs were connected properly, IBUS is a one-wire interface so I just used the RX pin, do I need to GND the TX, or leave it open?

Cheers,
Morgan

**Comment by MorGuux** [comment]
Just noticed, it was your diagrams on this repository that I used. I constructed both the RX only one first, then built the TX one also to try all options

**Comment by just-oblivious** [comment]
The source ID for the cluster is always 0x80, since the cluster is also the IBUS master it's already providing the necessary 12v pullup.

What does your code look like? You should be able to read IBUS data from the hardware serial port, then send it to the PC over another port.

Don

**Comment by MorGuux** [comment]
I found it somewhere. It uses the SoftwareSerial lib to connect to the PC using USB, and another Serial using pins 10 and 11 (where I had the IBUS connected)

#include <SoftwareSerial.h>

SoftwareSerial mySerial(10, 11); // RX, TX

void setup() {
  // Open serial communications and wait for port to open:
  Serial.begin(57600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }


  Serial.println("Goodnight moon!");

  // set the data rate for the SoftwareSerial port
  mySerial.begin(9600);
  mySerial.println("Hello, world?");
}

void loop() { // run over and over
  if (mySerial.available()) {
    Serial.write(mySerial.read());
  }
  if (Serial.available()) {
    mySerial.write(Serial.read());
  }
}
