### ISSUE TITLE
Override default MFL button functions

### ISSUE THREAD

**Issue by Eizo0x** [just-oblivious/arduino-ibustrx#3]
Hello,

Nice project! I've been playing around with the library and I was thinking is there any way to override default MFL/MID/Navi button functions, so for example when I click volume up, it won't increase volume but would send my specified iBus message?

Much appreciated, thanks!

**Comment by OBrown92** [comment]
I think this is not possible because a message sent by any device, is also received by any device. And if its volume up, the radio receives the message and will increase the volume.
